Refactor tpm functions into ExplicitTPM class
wmayner/pyphi pull request #69
Opened 2022-10-26 16:18 UTC by isacdaavid

This change leaves the TPM functionality and API almost untouched, while also refactoring it into a parent TPM class and an ExplicitTPM subclass, which takes the codebase closer to having another ImplicitTPM subclass with xarray.

Test results before and after these commits (I only see one lingering test I have yet to look at, `test_network_from_json`):

**Before**

============================================================================================= short test summary info =============================================================================================
FAILED test/test_subsystem_cause_effect_info.py::test_cause_info - TypeError: iit_4_small_phi_no_absolute_value() missing 1 required positional argument: 'state'
FAILED test/test_subsystem_cause_effect_info.py::test_effect_info - TypeError: iit_4_small_phi_no_absolute_value() missing 1 required positional argument: 'state'
FAILED test/test_subsystem_cause_effect_info.py::test_cause_effect_info - TypeError: iit_4_small_phi_no_absolute_value() missing 1 required positional argument: 'state'
FAILED test/test_subsystem_expand.py::test_expand_effect_repertoire - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-CAUSE-expected0] - assert Maximally-irreducible cause\n  φ = 1\n  Mechanism: [B]\n  Purview: [C]\n  Specified state(s): \n    [0]\n  Direction: CAUSE\n  MIP:\n     B     ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n    ┌─...
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-CAUSE-expected2] - assert Maximally-irreducible cause\n  φ = 0.5849625007212\n  Mechanism: [A,B]\n  Purview: [B,C]\n  Specified state(s): \n    [1, 0]\n  Direction: CAUSE\n  MIP:\n     A     B     ∅ \n    ─── ✕ ─── ✕ ───\n   ...
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-CAUSE-expected3] - assert Maximally-irreducible cause\n  φ = 0.5849625007212\n  Mechanism: [A,B,C]\n  Purview: [A,B,C]\n  Specified state(s): \n    [1, 1, 0]\n  Direction: CAUSE\n  MIP:\n     B    A,C    ∅ \n    ─── ✕ ─── ✕ ─...
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-EFFECT-expected4] - assert Maximally-irreducible effect\n  φ = 1/2\n  Mechanism: [B]\n  Purview: [A]\n  Specified state(s): \n    [0]\n  Direction: EFFECT\n  MIP:\n     B     ∅ \n    ─── ✕ ───\n     ∅     A \n  Repertoire:\n  ...
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-EFFECT-expected5] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [C]\n  Purview: [A,B]\n  Specified state(s): \n    [0, 0]\n    [1, 0]\n  Direction: EFFECT\n  MIP:\n     C     ∅ \n    ─── ✕ ───\n     ∅    A,B\n  ...
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-EFFECT-expected6] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [A,B]\n  Purview: [C]\n  Specified state(s): \n    [1]\n  Direction: EFFECT\n  MIP:\n    A,B    ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n  ...
FAILED test/test_subsystem_phi_max.py::test_find_mice[None-EFFECT-expected7] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [A,B,C]\n  Purview: [A,C]\n  Specified state(s): \n    [0, 1]\n  Direction: EFFECT\n  MIP:\n     A    B,C    ∅ \n    ─── ✕ ─── ✕ ───\n     ∅    A,C...
FAILED test/test_subsystem_phi_max.py::test_find_mice[cut8-CAUSE-expected8] - assert Maximally-irreducible cause\n  φ = 1\n  Mechanism: [B]\n  Purview: [C]\n  Specified state(s): \n    [0]\n  Direction: CAUSE\n  MIP:\n     B     ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n    ┌─...
FAILED test/test_subsystem_phi_max.py::test_find_mice[cut13-EFFECT-expected13] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [C]\n  Purview: [B]\n  Specified state(s): \n    [0]\n  Direction: EFFECT\n  MIP:\n     C     ∅ \n    ─── ✕ ───\n     ∅     B \n  Repertoire:\n    ...
FAILED test/test_subsystem_phi_max.py::test_find_mice[cut14-EFFECT-expected14] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [A,B]\n  Purview: [C]\n  Specified state(s): \n    [1]\n  Direction: EFFECT\n  MIP:\n    A,B    ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n  ...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-CAUSE-expected0] - assert Maximally-irreducible cause\n  φ = 1\n  Mechanism: [B]\n  Purview: [C]\n  Specified state(s): \n    [0]\n  Direction: CAUSE\n  MIP:\n     B     ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n    ┌─...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-CAUSE-expected2] - assert Maximally-irreducible cause\n  φ = 0.5849625007212\n  Mechanism: [A,B]\n  Purview: [B,C]\n  Specified state(s): \n    [1, 0]\n  Direction: CAUSE\n  MIP:\n     A     B     ∅ \n    ─── ✕ ─── ✕ ───\n   ...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-CAUSE-expected3] - assert Maximally-irreducible cause\n  φ = 0.5849625007212\n  Mechanism: [A,B,C]\n  Purview: [A,B,C]\n  Specified state(s): \n    [1, 1, 0]\n  Direction: CAUSE\n  MIP:\n     B    A,C    ∅ \n    ─── ✕ ─── ✕ ─...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-EFFECT-expected4] - assert Maximally-irreducible effect\n  φ = 1/2\n  Mechanism: [B]\n  Purview: [A]\n  Specified state(s): \n    [0]\n  Direction: EFFECT\n  MIP:\n     B     ∅ \n    ─── ✕ ───\n     ∅     A \n  Repertoire:\n  ...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-EFFECT-expected5] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [C]\n  Purview: [A,B]\n  Specified state(s): \n    [0, 0]\n    [1, 0]\n  Direction: EFFECT\n  MIP:\n     C     ∅ \n    ─── ✕ ───\n     ∅    A,B\n  ...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-EFFECT-expected6] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [A,B]\n  Purview: [C]\n  Specified state(s): \n    [1]\n  Direction: EFFECT\n  MIP:\n    A,B    ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n  ...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[None-EFFECT-expected7] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [A,B,C]\n  Purview: [A,C]\n  Specified state(s): \n    [0, 1]\n  Direction: EFFECT\n  MIP:\n     A    B,C    ∅ \n    ─── ✕ ─── ✕ ───\n     ∅    A,C...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[cut8-CAUSE-expected8] - assert Maximally-irreducible cause\n  φ = 1\n  Mechanism: [B]\n  Purview: [C]\n  Specified state(s): \n    [0]\n  Direction: CAUSE\n  MIP:\n     B     ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n    ┌─...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[cut13-EFFECT-expected13] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [C]\n  Purview: [B]\n  Specified state(s): \n    [0]\n  Direction: EFFECT\n  MIP:\n     C     ∅ \n    ─── ✕ ───\n     ∅     B \n  Repertoire:\n    ...
FAILED test/test_subsystem_phi_max.py::test_mic_or_mie[cut14-EFFECT-expected14] - assert Maximally-irreducible effect\n  φ = 1\n  Mechanism: [A,B]\n  Purview: [C]\n  Specified state(s): \n    [1]\n  Direction: EFFECT\n  MIP:\n    A,B    ∅ \n    ─── ✕ ───\n     ∅     C \n  Repertoire:\n  ...
FAILED test/test_subsystem_phi_max.py::test_phi_max[None-mechanism0-0.25] - assert False
FAILED test/test_subsystem_phi_max.py::test_phi_max[None-mechanism2-0.333333] - assert False
FAILED test/test_subsystem_phi_max.py::test_phi_max[None-mechanism3-0.4999995] - assert False
FAILED test/test_subsystem_small_phi.py::test_find_mip[CAUSE-subsystem0-None-mechanism0-purview0-expected0] - TypeError: iit_4_small_phi_no_absolute_value() missing 1 required positional argument: 'state'
FAILED test/test_subsystem_small_phi.py::test_find_mip[CAUSE-subsystem1-cut1-mechanism1-purview1-expected1] - TypeError: iit_4_small_phi_no_absolute_value() missing 1 required positional argument: 'state'
FAILED test/test_subsystem_small_phi.py::test_find_mip[EFFECT-subsystem2-None-mechanism2-purview2-expected2] - TypeError: iit_4_small_phi_no_absolute_value() missing 1 required positional argument: 'state'
FAILED test/test_subsystem_small_phi.py::test_find_mip[EFFECT-subsystem3-cut3-mechanism3 [...]

2022-10-26 16:56 UTC, wmayner requested changes

2022-10-26 16:56 UTC, wmayner commented on pyphi/network.py
> +        return hash((self._tpm.__hash__(), self._cm_hash))
Can just call builtin `hash` here

2022-10-26 16:56 UTC, wmayner commented on pyphi/tpm.py
> +    def _conditionally_independent(cls, tpm):
These validation methods can be normal methods rather than class methods, and can be called after building the TPM in the constructor

2022-10-27 15:56 UTC, isacdaavid commented on pyphi/network.py
> +        return hash((self._tpm.__hash__(), self._cm_hash))
Addressed in 340eedc

2022-10-27 16:30 UTC, wmayner approved these changes

2022-10-27 16:30 UTC, merged